### ISSUE TITLE
9/19亲测有效

### ISSUE THREAD

**Issue by ImYiFeng** [ularch/Cidaren_Automatic_Answer#2]
就是搞了个100分，班级排名断崖领先，有点尴尬😥

**Comment by Nihilismer** [comment]
兄弟我点击点我运行显示文件路径和from PyQt6.QtGui import QAction
ModuleNotFoundError: No module named 'PyQt6'怎么办啊

**Comment by ImYiFeng** [comment]
> 兄弟我点击点我运行显示文件路径和from PyQt6.QtGui import QAction ModuleNotFoundError: No module named 'PyQt6'怎么办啊

试试 `pip install PyQt6`

**Comment by ularch** [comment]
> 兄弟我点击点我运行显示文件路径和from PyQt6.QtGui import QAction
> ModuleNotFoundError: No module named 'PyQt6'怎么办啊

缺少必要库，检查是否正确配置环境

**Comment by Nihilismer** [comment]
> > 兄弟我点击点我运行显示文件路径和from PyQt6.QtGui import QAction ModuleNotFoundError: No module named 'PyQt6'怎么办啊
> 
> 试试 `pip install PyQt6`

谢谢

**Comment by Nihilismer** [comment]
> > 兄弟我点击点我运行显示文件路径和from PyQt6.QtGui import QAction
> > ModuleNotFoundError: No module named 'PyQt6'怎么办啊
> 
> 缺少必要库，检查是否正确配置环境

谢谢
