### ISSUE TITLE
应用突然中断

### ISSUE THREAD

**Issue by coicc** [ularch/Cidaren_Automatic_Answer#4]
<img width="517" alt="{709B6AD2-C3EC-4D99-8407-7A58D43FCD94}" src="https://github.com/user-attachments/assets/f8c5ffc4-c208-429e-ba33-ecb5982d8174" />
出现了到“英译汉”题目程序自动退出的问题，请问这是为什么？

**Comment by Bvzz00** [comment]
同

**Comment by ularch** [comment]
已修复
