### ISSUE TITLE
一点登录就闪退怎么办

### ISSUE THREAD

**Issue by cbvxgbv** [ularch/Cidaren_Automatic_Answer#5]
![屏幕截图 2024-12-21 021637](https://github.com/user-attachments/assets/aea12656-0e10-41f9-9465-8819a973de67)
如图，我已经按要求获取token之后关掉那个获取token的软件了，还是登录就闪退

**Comment by cbvxgbv** [comment]
关了，我还特地打开任务管理器确认了一下，确实关了。
后来我开着那个软件对比了一下，最下面的报错和这个报错是不一样，说明应该不是获取token的没关

**Comment by ularch** [comment]
邮件练习harold.lach.lei@gmail.com

**Comment by ularch** [comment]
将request_header.py文件里的headers变量中的"Accept_Encoding"参数中的, br删掉
